# Generated by Django 2.1.5 on 2019-02-22 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(default='Oakridge International School (Newton Campus)', max_length=60),
        ),
    ]
